name: Build Android APK

on:
  push:
    branches:
      - main  # يمكنك تغييره لفرع آخر إذا كنت تستخدم فرعًا مختلفًا

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'  # أو يمكنك استخدام 'temurin' حسب التوزيعة التي تحتاجها
          java-version: '11'

      - name: Install Free Pascal Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y fpc

      - name: Build APK
        run: |
          fpc -Mdelphi MainActivity.pas  # بناء مشروع Pascal

      - name: Archive APK
        run: |
          mkdir output
          mv *.apk output/
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp
          path: output/*.apk
